### ISSUE TITLE
取消重复请求的问题

### ISSUE THREAD

**Issue by yangangzhang** [verymuch/very-axios#2]
`if (isDuplicatedType) return;`
在代码186行的地方，过滤重复请求的错误，这个地方，是不是也应该return Promise.reject()，而不应该是直接return；否则，直接走到了请求回调的成功方法中
比如下面：
`Promise.reject(123).then((val)=> {
  console.log('val', val)
},(err) => {
  console.log('err', err)
  return 3333
}).then((val1)=> {
  console.log('val1', val1)
},(err1) => {
  console.log('err1', err1)
})`
最后打印结果是val1, 333

**Comment by verymuch** [comment]
是的，你说的对，这个地方直接 `return` 存在问题，会走到成功的回调里。我计划返回如下内容，方便从你使用的角度反馈一下有没有其他影响不？
```
const duolicatedErrTip = 'VeryAxios: 已取消重复请求'
return Promise.reject(duolicatedErrTip)
```

**Comment by yangangzhang** [comment]
> 是的，你说的对，这个地方直接 `return` 存在问题，会走到成功的回调里。我计划返回如下内容，方便从你使用的角度反馈一下有没有其他影响不？
> 
> ```
> const duolicatedErrTip = 'VeryAxios: 已取消重复请求'
> return Promise.reject(duolicatedErrTip)
> ```

我也是这样修改的，目前没有发现其他问题，有问题向您在反馈

**Comment by verymuch** [comment]
已发版，版本为 v0.1.15。感谢反馈。

错误提示更新如下，支持了中英文

![image](https://user-images.githubusercontent.com/9148095/103615071-e60f0500-4f64-11eb-809c-9d1666567d8b.png)
